### ISSUE TITLE
If epochs are defined, folder names stay default

### ISSUE THREAD

**Issue by nathanegraham** [robbiebarrat/rapping-neural-network#10]
First off, very nifty script and it's easy to work with. Maybe I'm misunderstanding something but when I define a specific epoch count

```
training = 1 #training of 0 means you just want to have it write a rap - training of 1 will train the network on the contents of lyrics.txt
epoch = 105 #this is just the number of the folder you would like to load (folder contains the trained net and rhymes)
```
I still get folders 100, 200, etc. (e.g., "just wrote 100/...").

Another question is when the training concludes? I'm up to epoch 400 now.

**Comment by robbiebarrat** [comment]
Hey - glad you like it. I realize that this stuff isn't very clear in the readme, I'll update it soon.

The variable "epoch" is only for when you're generating raps (while training = 0). Right now you're in "training mode", which is an infinite loop. It'll keep writing folders of trained nets until you stop the program, and you can stop it whenever you see fit (usually ~400 is plenty). After you have a folder written that you want to use (in your case, 400) just specify that folder by making epoch = 400, change training so it equals 0, and then run the program to generate raps.

Another thing - you don't *need* to train it- the trained nets that come with the repo are already trained on the full dataset of kanye lyrics, so unless you're trying to change how it rhymes, or write raps in a different language, you really don't need to train it.

**Comment by nathanegraham** [comment]
Thanks, Robbie! Very helpful. I'll give that a try.

**Comment by robbiebarrat** [comment]
no problem! have fun rapping
