### ISSUE TITLE
Freezing on word by word

### ISSUE THREAD

**Issue by ChoclateRain** [robbiebarrat/rapping-neural-network#12]
I have edited my lyrics file so that when training the error message:
("Hm, for some reason we couldn't do anything with this line - remove symbols from it and try again: ")
**doesnt** show but when generating mode is on word by word still freezes
line by line works though

**Comment by robbiebarrat** [comment]
sorry about that! just updated it - try cloning the repo again and using the updated version.

This was the first big machine learning project I really did. It's in need of a total rewrite because it's plagued by errors like this, haha. i'll get around to it soon though.

**Comment by ChoclateRain** [comment]
Its still processing currently i hope its not frozen again (Think it is, been 30 minutes) but reading the terminal there are a couple bugs: 

**1**. _After the "Done Building the text model and markov chain" part  each line starts with ". " and there are some duplicates_ 
'Done the markov chain part... Building the model...Done building the text model!
. Smoke fallin from the saw mill city. vocally nicer than dope fatkiss.
2
None
3
None
4
. Sawed from a different dimension.
5
. Fightin, writing, like mic Tyson, The size of two bison with a sequel.
6
. Fightin, writing, like mic Tyson, The size of two bison with a sequel.
'
**2**. _The part "Alright, building the list of all the rhymes - here are the words that have to be taken into account;"
Is showing the word 'none' a couple of times even thought the word 'none' is not in my lyrics.txt
It is also showing duplicates (Dunno if thats norm)_
'none
none
dimension
diss
priceless
dimension
eyelids
diss
deal
maxin
maxin
doses
fattest
priceless
eyelids
life
deal
life
vacuum
vacuum
fattest
dragon
'

**Comment by robbiebarrat** [comment]
Sorry - Give me a few more days, I'm about to put up a rewrite/overhaul of the project in Keras.

**Comment by robbiebarrat** [comment]
Alright - expect the rewritten version up either later today or tomorrow...

**Comment by robbiebarrat** [comment]
Alright - sorry it's taken so long, but the new release is out and none of your issues should be a problem any more because everything has been rewritten
