### ISSUE TITLE
Unicode decode error

### ISSUE THREAD

**Issue by bensdm** [robbiebarrat/rapping-neural-network#16]
Hi,
Great job, i am trying to generate raps with default kanye lines but i have the following error:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 42992: character maps to <undefined>

thanks for your help

**Comment by robbiebarrat** [comment]
Could you please paste in the full error message? I think I've ran into something similar before...

**Comment by bensdm** [comment]
File "C:\Anaconda3\envs\tensorflow\lib\encodings\cp1252.py", line 23, in
decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4299
2: character maps to <undefined>

thanks

**Comment by robbiebarrat** [comment]
Are you on a mac? Also "Anaconda3" - are you using python 3? If so, please switch to 2.7.

Assuming you're on python 2.7 - you could try adding the `encoding="utf8"` argument to all of the parts where files are `open()`ed - like `file = open(filename, encoding="utf8", "r")`

**Comment by bensdm** [comment]
thanks for your response, now i've the following error:
reverselist = sorted(reverselist)
TypeError: '<' not supported between instances of 'bytes' and 'str'

**Comment by bensdm** [comment]
i am on windows and cant install tensorflow with python 2.7 on windows...

**Comment by robbiebarrat** [comment]
Sorry for the delay in response; glad you got it fixed. Sometimes the "remain the same during the whole rap" thing happens; but not a large percentage of the time.
