### ISSUE TITLE
Error in running model.py

### ISSUE THREAD

**Issue by lima12345** [robbiebarrat/rapping-neural-network#19]
When I try to generate the lyrics, I get the error:

ValueError: Layer #0 (named "lstm_1" in the current model) was found to correspond to layer lstm_1 in the save file. However the new layer lstm_1 expects 12 weights, but the saved weights have 3 elements.

How can I correct this?

**Comment by robbiebarrat** [comment]
make sure that your versions correspond correctly. 
```
Keras==1.2.2
numpy==1.12.1
```


you can do so by opening a python shell, typing `import keras` and then `keras.__version__` - same for numpy.

**Comment by lima12345** [comment]
my Keras version is 1.2.3, and numpy is 1.13.3-- how do I go about fixing this?

**Comment by Omkar1206** [comment]
Yeah even I am getting the same error, but I am using python3 instead of 2. Is that the problem?

**Comment by rushh** [comment]
Did you guys manage to fix the issue?

**Comment by Omkar1206** [comment]
Nope!

**Comment by ak9250** [comment]
gettin the same error using python 2 in google colab here in the notebook https://colab.research.google.com/drive/1ezq8WgQxahTgnRB5qAF6EqlpmMgtsmIB

**Comment by robbiebarrat** [comment]
Here's a colab notebook I made that runs the network; will add this to the readme in a second.

https://goo.gl/GHSWzZ

**Comment by ghost** [comment]
Awesome thanks Robbie, one issue I ran into the notebook you linked is the main(depth) should be run after its defined, pushed that cell down after making a copy of yours and seems to be running fine now in this notebook 
https://colab.research.google.com/drive/1tTknOR6jI2ZxCtMCcyWaGoko-i6yTUVy

**Comment by robbiebarrat** [comment]
aah sorry - i wrote that for a class I'm TAing and i put the huge cell at the bottom so they wouldn't have to scroll past it... I'll move it right now.
