### ISSUE TITLE
Model Architecture ?

### ISSUE THREAD

**Issue by YuChunLOL** [robbiebarrat/rapping-neural-network#5]
Hello, first of all, this work is cool ! Nice job !
I would like to ask what model is used by this project ?

**Comment by robbiebarrat** [comment]
Thank you for the appreciation! It's a small recurrent neural network that uses sigmoid functions in the hidden layers. I made the actual neural network using pybrain, which is a great python library that lets you make neural networks quite easily. I'd check out pybrain (pybrain.org) if you're interested in writing your own neural networks.
Does that answer your question?

**Comment by ablange** [comment]
Robbie,

Just saw you on the Today show, Dude your stuff is super inspiring, excited to see what you'll do next! 

Best,
AL
