### ISSUE TITLE
How did you generate the final mp3 for the video?

### ISSUE THREAD

**Issue by jungletech** [robbiebarrat/rapping-neural-network#7]
I got my terminal to play it, how did u save that file?

**Comment by robbiebarrat** [comment]
I used Audacity and simply recorded the output of my computer's speakers. Any type of audio capturing tool that can record the speaker-out should work - I know Audacity worked for me on Linux, if you're on windows let me know if it works there, too. I'll make a video soon detailing the process from downloading the program to making a song.
