### ISSUE TITLE
Pybrain help

### ISSUE THREAD

**Issue by Borzborz** [robbiebarrat/rapping-neural-network#9]
I'm having a problem running deeprap.py in terminal, I keep getting a "No module named 'structure'" error. And I have Pybrain version 0.3.3 installed on my mac.

**Comment by robbiebarrat** [comment]
Can you paste the output of terminal when you try to run deeprap.py here? Also; what operating system are you using?

**Comment by Borzborz** [comment]
<img width="568" alt="screen shot 2017-03-24 at 7 12 04 am" src="https://cloud.githubusercontent.com/assets/26649854/24382149/6f0f3ba0-1322-11e7-8997-b37ae2f23aad.png">
 im running a macOS Sierra

**Comment by robbiebarrat** [comment]
download the .zip file of the entire pybrain project from github at https://github.com/pybrain/pybrain and after unzipping it, go inside it from terminal and run 
    
    python setup.py install

that should work - let me know.

**Comment by robbiebarrat** [comment]
Guess it worked, considering it's been ~2 weeks...
Hope all is well!
